services:
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
      # Enable BuildKit for better caching
      cache_from:
        - bawabah-ai:latest
    ports:
      - 6060:6060
    # Add volume for Hugging Face cache to persist between builds
    volumes:
      - huggingface_cache:/home/appuser/.cache/huggingface

volumes:
  huggingface_cache:

