services:
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
      # Enable BuildKit for better caching
      cache_from:
        - bawabah-ai:latest
    ports:
      - 6060:6060
    # Add volume for Hugging Face cache to persist between builds
    volumes:
      - huggingface_cache:/home/appuser/.cache/huggingface
      
    environment:
      - DOLPHIN_MODEL_PATH=/app/external/Dolphin/hf_model


volumes:
  huggingface_cache:



